---
language: ruby
cache: bundler
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
  - 2.4.10
  - jruby-9.2.12.0
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.2.12.0
before_install: gem install bundler -v 2.1.4
